server:
 port: 8081
#配置服务的名字
spring:
 application:
  name: eureka-server
#自己注册自己
eureka:
 client:
  registerWithEureka: false #是否要注册到其他Server上   registerWithEureka等同于register_with_eureka
  fetchRegistry: false  #是否需要拉取服务信息       fetchRegistry等同于 fetch-registry
  service-url:
   defaultZone: http://127.0.0.1:8081/eureka/
